DROP TABLE IF EXISTS respostas_dadas CASCADE;
DROP TABLE IF EXISTS dificuldades CASCADE;
DROP TABLE IF EXISTS submissao CASCADE;
DROP TABLE IF EXISTS respostas CASCADE;
DROP TABLE IF EXISTS perguntas CASCADE;
DROP TABLE IF EXISTS quizzes CASCADE;
DROP TABLE IF EXISTS tema CASCADE;
DROP TABLE IF EXISTS utilizadores CASCADE;